import type { Quote, Order, Customer, SalesRep, Product, QuoteStatus, OrderStatus, CustomerInvoice, InvoiceLineItem } from './types'

// Sample customers
export const sampleCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'ACME Construction',
    email: 'purchasing@acmeconstruction.com',
    phone: '512-555-0100',
    type: 'B2B Contractor',
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-123',
    credit_limit: 50000,
  },
  {
    id: 'cust-2',
    name: 'BuildCo Inc',
    email: 'orders@buildco.com',
    phone: '512-555-0200',
    type: 'Distributor',
    tax_exempt: false,
    credit_limit: 100000,
  },
  {
    id: 'cust-3',
    name: 'Steel Supply Co',
    email: 'procurement@steelsupply.com',
    phone: '512-555-0300',
    type: 'Retailer',
    tax_exempt: false,
    credit_limit: 25000,
  },
  {
    id: 'cust-4',
    name: 'Regional Builders',
    email: 'buying@regionalbuilders.com',
    phone: '512-555-0400',
    type: 'B2B Contractor',
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-456',
    credit_limit: 75000,
  },
]

// Sample sales rep
export const sampleSalesRep: SalesRep = {
  id: 'rep-1',
  name: 'Sarah Chen',
  email: 'sarah.chen@camber.ai',
  phone: '512-555-0001',
}

// Product categories
export const productCategories = [
  {
    id: 'steel',
    name: 'Steel',
    subcategories: [
      { id: 'rebar', name: 'Rebar', count: 24 },
      { id: 'mesh', name: 'Wire Mesh', count: 12 },
      { id: 'beams', name: 'Steel Beams', count: 18 },
    ]
  },
  {
    id: 'concrete',
    name: 'Concrete',
    subcategories: [
      { id: 'ready-mix', name: 'Ready Mix', count: 8 },
      { id: 'bagged', name: 'Bagged Mix', count: 15 },
      { id: 'additives', name: 'Additives', count: 10 },
    ]
  },
  {
    id: 'lumber',
    name: 'Lumber',
    subcategories: [
      { id: 'dimensional', name: 'Dimensional', count: 45 },
      { id: 'plywood', name: 'Plywood', count: 20 },
      { id: 'treated', name: 'Treated', count: 30 },
    ]
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    subcategories: [
      { id: 'pipe', name: 'Pipe', count: 35 },
      { id: 'fittings', name: 'Fittings', count: 120 },
      { id: 'valves', name: 'Valves', count: 40 },
    ]
  },
]

// Sample products with enhanced construction materials focus
export const sampleProducts: Product[] = [
  // Rebar products
  {
    id: 'prod-1',
    sku: 'RB500-20',
    manufacturer_sku: 'US-RB500-20',
    name: '1/2" Rebar Grade 60',
    description: '#4 Rebar, 1/2" diameter, Grade 60, 20ft length',
    unit_price: 18.25,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 450,
    category: ['Steel', 'Rebar'],
    specifications: {
      diameter: '1/2 inch',
      grade: 'Grade 60',
      length: '20 ft',
      weight: '13.4 lbs',
      astm: 'A615',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 300 },
      { location: 'North Branch', quantity: 150 },
    ],
    alternatives: ['prod-2', 'prod-3'],
  },
  {
    id: 'prod-2',
    sku: 'RB500-40',
    manufacturer_sku: 'US-RB500-40',
    name: '1/2" Rebar Grade 40',
    description: '#4 Rebar, 1/2" diameter, Grade 40, 20ft length',
    unit_price: 16.50,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 200,
    category: ['Steel', 'Rebar'],
    specifications: {
      diameter: '1/2 inch',
      grade: 'Grade 40',
      length: '20 ft',
      weight: '13.4 lbs',
      astm: 'A615',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 200 },
    ],
    alternatives: ['prod-1', 'prod-3'],
  },
  {
    id: 'prod-3',
    sku: 'RB500-EP',
    manufacturer_sku: 'US-RB500-EP',
    name: '1/2" Epoxy Coated Rebar',
    description: '#4 Rebar, 1/2" diameter, Epoxy coated, Grade 60, 20ft',
    unit_price: 24.75,
    unit_of_measure: 'EA',
    inventory_status: 'low_stock',
    available_quantity: 50,
    lead_time_days: 5,
    category: ['Steel', 'Rebar'],
    specifications: {
      diameter: '1/2 inch',
      grade: 'Grade 60',
      coating: 'Epoxy',
      length: '20 ft',
      weight: '13.8 lbs',
      astm: 'A615/A775',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 50 },
    ],
    alternatives: ['prod-1'],
  },
  {
    id: 'prod-4',
    sku: 'RB625-20',
    manufacturer_sku: 'US-RB625-20',
    name: '5/8" Rebar Grade 60',
    description: '#5 Rebar, 5/8" diameter, Grade 60, 20ft length',
    unit_price: 22.50,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 300,
    category: ['Steel', 'Rebar'],
    specifications: {
      diameter: '5/8 inch',
      grade: 'Grade 60',
      length: '20 ft',
      weight: '20.9 lbs',
      astm: 'A615',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 200 },
      { location: 'North Branch', quantity: 100 },
    ],
    alternatives: ['prod-5'],
  },
  {
    id: 'prod-5',
    sku: 'RB750-20',
    manufacturer_sku: 'US-RB750-20',
    name: '3/4" Rebar Grade 60',
    description: '#6 Rebar, 3/4" diameter, Grade 60, 20ft length',
    unit_price: 32.25,
    unit_of_measure: 'EA',
    inventory_status: 'special_order',
    available_quantity: 0,
    lead_time_days: 7,
    category: ['Steel', 'Rebar'],
    specifications: {
      diameter: '3/4 inch',
      grade: 'Grade 60',
      length: '20 ft',
      weight: '30.0 lbs',
      astm: 'A615',
    },
    stock_locations: [],
    alternatives: ['prod-4'],
  },
  
  // Concrete products
  {
    id: 'prod-6',
    sku: 'CONC-5000',
    manufacturer_sku: 'QC-5000-CY',
    name: '5000 PSI Concrete Mix',
    description: 'High-strength ready mix concrete, 5000 PSI, per cubic yard',
    unit_price: 145.00,
    unit_of_measure: 'CY',
    inventory_status: 'in_stock',
    available_quantity: 999,
    category: ['Concrete', 'Ready Mix'],
    specifications: {
      strength: '5000 PSI',
      slump: '4 inch',
      aggregate: '3/4 inch',
      cure_time: '28 days',
    },
    stock_locations: [
      { location: 'Batch Plant', quantity: 999 },
    ],
    alternatives: ['prod-7', 'prod-8'],
  },
  {
    id: 'prod-7',
    sku: 'CONC-4000',
    manufacturer_sku: 'QC-4000-CY',
    name: '4000 PSI Concrete Mix',
    description: 'Standard ready mix concrete, 4000 PSI, per cubic yard',
    unit_price: 135.00,
    unit_of_measure: 'CY',
    inventory_status: 'in_stock',
    available_quantity: 999,
    category: ['Concrete', 'Ready Mix'],
    specifications: {
      strength: '4000 PSI',
      slump: '4 inch',
      aggregate: '3/4 inch',
      cure_time: '28 days',
    },
    stock_locations: [
      { location: 'Batch Plant', quantity: 999 },
    ],
    alternatives: ['prod-6', 'prod-8'],
  },
  {
    id: 'prod-8',
    sku: 'CONC-3000',
    manufacturer_sku: 'QC-3000-CY',
    name: '3000 PSI Concrete Mix',
    description: 'Standard ready mix concrete, 3000 PSI, per cubic yard',
    unit_price: 125.00,
    unit_of_measure: 'CY',
    inventory_status: 'in_stock',
    available_quantity: 999,
    category: ['Concrete', 'Ready Mix'],
    specifications: {
      strength: '3000 PSI',
      slump: '4 inch',
      aggregate: '3/4 inch',
      cure_time: '28 days',
    },
    stock_locations: [
      { location: 'Batch Plant', quantity: 999 },
    ],
    alternatives: ['prod-6', 'prod-7'],
  },
  
  // Bagged concrete
  {
    id: 'prod-9',
    sku: 'BAG-CONC-80',
    manufacturer_sku: 'QC-BAG-80',
    name: 'Concrete Mix 80lb Bag',
    description: 'Pre-mixed concrete, just add water, 80 pound bag',
    unit_price: 8.99,
    unit_of_measure: 'BAG',
    inventory_status: 'in_stock',
    available_quantity: 200,
    category: ['Concrete', 'Bagged Mix'],
    specifications: {
      weight: '80 lbs',
      coverage: '0.6 cu ft',
      strength: '4000 PSI',
      mix_ratio: '3 quarts water per bag',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 150 },
      { location: 'North Branch', quantity: 50 },
    ],
    alternatives: ['prod-10'],
  },
  {
    id: 'prod-10',
    sku: 'BAG-CONC-50',
    manufacturer_sku: 'QC-BAG-50',
    name: 'Fast Setting Concrete 50lb',
    description: 'Fast-setting concrete mix, sets in 20-40 minutes, 50lb bag',
    unit_price: 7.49,
    unit_of_measure: 'BAG',
    inventory_status: 'in_stock',
    available_quantity: 100,
    category: ['Concrete', 'Bagged Mix'],
    specifications: {
      weight: '50 lbs',
      coverage: '0.375 cu ft',
      set_time: '20-40 minutes',
      strength: '4000 PSI',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 100 },
    ],
    alternatives: ['prod-9'],
  },
  
  // Lumber products
  {
    id: 'prod-11',
    sku: 'LUM-2X4-8',
    manufacturer_sku: 'SPF-2X4-8',
    name: '2x4 Lumber 8ft',
    description: 'Standard framing lumber, 2x4x8 feet, kiln dried',
    unit_price: 5.98,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 500,
    category: ['Lumber', 'Dimensional'],
    specifications: {
      actual_size: '1.5" x 3.5"',
      nominal_size: '2" x 4"',
      length: '8 ft',
      species: 'SPF',
      grade: 'Stud',
      moisture: '19% or less',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 350 },
      { location: 'North Branch', quantity: 150 },
    ],
    alternatives: ['prod-12', 'prod-13'],
  },
  {
    id: 'prod-12',
    sku: 'LUM-2X4-10',
    manufacturer_sku: 'SPF-2X4-10',
    name: '2x4 Lumber 10ft',
    description: 'Standard framing lumber, 2x4x10 feet, kiln dried',
    unit_price: 7.48,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 300,
    category: ['Lumber', 'Dimensional'],
    specifications: {
      actual_size: '1.5" x 3.5"',
      nominal_size: '2" x 4"',
      length: '10 ft',
      species: 'SPF',
      grade: 'Stud',
      moisture: '19% or less',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 200 },
      { location: 'North Branch', quantity: 100 },
    ],
    alternatives: ['prod-11', 'prod-13'],
  },
  {
    id: 'prod-13',
    sku: 'LUM-2X4-12',
    manufacturer_sku: 'SPF-2X4-12',
    name: '2x4 Lumber 12ft',
    description: 'Standard framing lumber, 2x4x12 feet, kiln dried',
    unit_price: 8.98,
    unit_of_measure: 'EA',
    inventory_status: 'low_stock',
    available_quantity: 50,
    lead_time_days: 3,
    category: ['Lumber', 'Dimensional'],
    specifications: {
      actual_size: '1.5" x 3.5"',
      nominal_size: '2" x 4"',
      length: '12 ft',
      species: 'SPF',
      grade: 'Stud',
      moisture: '19% or less',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 50 },
    ],
    alternatives: ['prod-11', 'prod-12'],
  },
  {
    id: 'prod-14',
    sku: 'LUM-2X6-8',
    manufacturer_sku: 'SPF-2X6-8',
    name: '2x6 Lumber 8ft',
    description: 'Standard framing lumber, 2x6x8 feet, kiln dried',
    unit_price: 8.98,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 400,
    category: ['Lumber', 'Dimensional'],
    specifications: {
      actual_size: '1.5" x 5.5"',
      nominal_size: '2" x 6"',
      length: '8 ft',
      species: 'SPF',
      grade: 'Stud',
      moisture: '19% or less',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 250 },
      { location: 'North Branch', quantity: 150 },
    ],
    alternatives: ['prod-15'],
  },
  {
    id: 'prod-15',
    sku: 'PLY-CDX-1/2',
    manufacturer_sku: 'CDX-PLY-48',
    name: '1/2" CDX Plywood',
    description: 'CDX plywood sheathing, 1/2" x 4\' x 8\', exterior grade',
    unit_price: 32.98,
    unit_of_measure: 'SHEET',
    inventory_status: 'in_stock',
    available_quantity: 150,
    category: ['Lumber', 'Plywood'],
    specifications: {
      thickness: '1/2 inch',
      width: '4 ft',
      length: '8 ft',
      grade: 'CDX',
      plies: '5',
      exposure: 'Exterior',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 100 },
      { location: 'North Branch', quantity: 50 },
    ],
    alternatives: ['prod-16'],
  },
  {
    id: 'prod-16',
    sku: 'PLY-OSB-7/16',
    manufacturer_sku: 'OSB-716-48',
    name: '7/16" OSB Sheathing',
    description: 'Oriented Strand Board, 7/16" x 4\' x 8\', structural sheathing',
    unit_price: 24.98,
    unit_of_measure: 'SHEET',
    inventory_status: 'in_stock',
    available_quantity: 200,
    category: ['Lumber', 'Plywood'],
    specifications: {
      thickness: '7/16 inch',
      width: '4 ft',
      length: '8 ft',
      type: 'OSB',
      span_rating: '24/16',
      exposure: 'Exposure 1',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 150 },
      { location: 'North Branch', quantity: 50 },
    ],
    alternatives: ['prod-15'],
  },
  
  // Plumbing products
  {
    id: 'prod-17',
    sku: 'PVC-4-20',
    manufacturer_sku: 'SCH40-PVC-4',
    name: '4" PVC Pipe Schedule 40',
    description: 'Schedule 40 PVC pipe, 4 inch diameter, 20ft length',
    unit_price: 45.50,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 150,
    category: ['Plumbing', 'Pipe'],
    specifications: {
      diameter: '4 inch',
      schedule: '40',
      length: '20 ft',
      material: 'PVC',
      pressure_rating: '220 PSI',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 100 },
      { location: 'North Branch', quantity: 50 },
    ],
    alternatives: ['prod-18'],
  },
  {
    id: 'prod-18',
    sku: 'PVC-3-20',
    manufacturer_sku: 'SCH40-PVC-3',
    name: '3" PVC Pipe Schedule 40',
    description: 'Schedule 40 PVC pipe, 3 inch diameter, 20ft length',
    unit_price: 32.50,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 100,
    category: ['Plumbing', 'Pipe'],
    specifications: {
      diameter: '3 inch',
      schedule: '40',
      length: '20 ft',
      material: 'PVC',
      pressure_rating: '260 PSI',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 100 },
    ],
    alternatives: ['prod-17', 'prod-19'],
  },
  {
    id: 'prod-19',
    sku: 'CPVC-3/4-10',
    manufacturer_sku: 'CPVC-075-10',
    name: '3/4" CPVC Pipe',
    description: 'CPVC hot water pipe, 3/4 inch diameter, 10ft length',
    unit_price: 12.98,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 200,
    category: ['Plumbing', 'Pipe'],
    specifications: {
      diameter: '3/4 inch',
      length: '10 ft',
      material: 'CPVC',
      temperature_rating: '200°F',
      pressure_rating: '100 PSI @ 180°F',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 150 },
      { location: 'North Branch', quantity: 50 },
    ],
    alternatives: ['prod-20'],
  },
  {
    id: 'prod-20',
    sku: 'PEX-1/2-100',
    manufacturer_sku: 'PEX-A-050-100',
    name: '1/2" PEX-A Tubing 100ft',
    description: 'PEX-A flexible water tubing, 1/2 inch, 100ft coil, red',
    unit_price: 54.98,
    unit_of_measure: 'COIL',
    inventory_status: 'in_stock',
    available_quantity: 75,
    category: ['Plumbing', 'Pipe'],
    specifications: {
      diameter: '1/2 inch',
      length: '100 ft',
      material: 'PEX-A',
      color: 'Red',
      temperature_rating: '200°F',
      pressure_rating: '160 PSI @ 73°F',
    },
    stock_locations: [
      { location: 'Main Yard', quantity: 50 },
      { location: 'North Branch', quantity: 25 },
    ],
    alternatives: ['prod-19'],
  },
]

// Sample quotes with different statuses
export const sampleQuotes: Quote[] = [
  {
    id: 'quote-1',
    quote_number: 'Q-2024-1001',
    version: 1,
    status: 'draft',
    customer: sampleCustomers[0],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-1',
        product: sampleProducts[0],
        quantity: 25,
        unit_price: 45.50,
        subtotal: 1137.50,
        confidence_score: 95,
      },
      {
        id: 'line-2',
        product: sampleProducts[1],
        quantity: 15,
        unit_price: 12.75,
        subtotal: 191.25,
        confidence_score: 88,
      },
    ],
    billing_address: {
      street: '123 Main St',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
    },
    job_site_address: {
      street: '456 Construction Way',
      city: 'Round Rock',
      state: 'TX',
      zip: '78664',
    },
    project_name: 'Westlake Office Complex - Phase 2',
    subtotal: 1328.75,
    discount: {
      percentage: 5,
      amount: 66.44,
      reason: 'Volume discount',
    },
    tax_rate: 0,
    tax_amount: 0,
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-123',
    shipping_cost: 125.00,
    total: 1387.31,
    valid_until: new Date('2024-02-15'),
    created_at: new Date('2024-01-15T10:30:00'),
    updated_at: new Date('2024-01-15T10:30:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'draft' as QuoteStatus,
        timestamp: new Date('2024-01-15T10:30:00'),
      },
    ],
    notes: 'Customer requested delivery by end of month',
  },
  {
    id: 'quote-2',
    quote_number: 'Q-2024-1000',
    version: 2,
    status: 'sent',
    customer: sampleCustomers[1],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-3',
        product: sampleProducts[2],
        quantity: 100,
        unit_price: 18.25,
        subtotal: 1825.00,
        confidence_score: 92,
      },
      {
        id: 'line-4',
        product: sampleProducts[3],
        quantity: 50,
        unit_price: 8.99,
        subtotal: 449.50,
        confidence_score: 90,
      },
    ],
    billing_address: {
      street: '789 Industrial Blvd',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
    },
    subtotal: 2274.50,
    tax_rate: 0.0825,
    tax_amount: 187.65,
    tax_exempt: false,
    shipping_cost: 200.00,
    total: 2662.15,
    valid_until: new Date('2024-02-10'),
    created_at: new Date('2024-01-15T09:00:00'),
    updated_at: new Date('2024-01-15T09:30:00'),
    sent_at: new Date('2024-01-15T09:30:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'draft' as QuoteStatus,
        timestamp: new Date('2024-01-15T09:00:00'),
      },
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2024-01-15T09:30:00'),
        changed_by: 'Sarah Chen',
      },
    ],
  },
  {
    id: 'quote-3',
    quote_number: 'Q-2024-0999',
    version: 1,
    status: 'accepted',
    customer: sampleCustomers[2],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-5',
        product: sampleProducts[0],
        quantity: 50,
        unit_price: 45.50,
        subtotal: 2275.00,
        confidence_score: 98,
      },
    ],
    billing_address: {
      street: '321 Commerce St',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
    },
    subtotal: 2275.00,
    tax_rate: 0.0825,
    tax_amount: 187.69,
    tax_exempt: false,
    shipping_cost: 150.00,
    total: 2612.69,
    valid_until: new Date('2024-02-05'),
    created_at: new Date('2024-01-14T14:00:00'),
    updated_at: new Date('2024-01-14T16:00:00'),
    sent_at: new Date('2024-01-14T14:30:00'),
    accepted_at: new Date('2024-01-14T16:00:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2024-01-14T14:30:00'),
      },
      {
        from: 'sent' as QuoteStatus,
        to: 'accepted' as QuoteStatus,
        timestamp: new Date('2024-01-14T16:00:00'),
        changed_by: 'John Smith',
        notes: 'PO# SS-2024-789',
      },
    ],
  },
  {
    id: 'quote-4',
    quote_number: 'Q-2024-0998',
    version: 1,
    status: 'converted',
    customer: sampleCustomers[3],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-6',
        product: sampleProducts[1],
        quantity: 100,
        unit_price: 12.75,
        subtotal: 1275.00,
        confidence_score: 100,
      },
      {
        id: 'line-7',
        product: sampleProducts[3],
        quantity: 75,
        unit_price: 8.99,
        subtotal: 674.25,
        confidence_score: 100,
      },
    ],
    billing_address: {
      street: '555 Builder Way',
      city: 'San Antonio',
      state: 'TX',
      zip: '78201',
    },
    job_site_address: {
      street: '1000 Project Rd',
      city: 'New Braunfels',
      state: 'TX',
      zip: '78130',
    },
    project_name: 'River Walk Extension',
    subtotal: 1949.25,
    tax_rate: 0,
    tax_amount: 0,
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-456',
    shipping_cost: 175.00,
    total: 2124.25,
    valid_until: new Date('2024-02-01'),
    created_at: new Date('2024-01-13T10:00:00'),
    updated_at: new Date('2024-01-13T15:00:00'),
    sent_at: new Date('2024-01-13T10:30:00'),
    accepted_at: new Date('2024-01-13T14:00:00'),
    converted_at: new Date('2024-01-13T15:00:00'),
    status_history: [
      {
        from: 'sent' as QuoteStatus,
        to: 'accepted' as QuoteStatus,
        timestamp: new Date('2024-01-13T14:00:00'),
        changed_by: 'Mike Johnson',
        notes: 'PO# RB-2024-2345',
      },
      {
        from: 'accepted' as QuoteStatus,
        to: 'converted' as QuoteStatus,
        timestamp: new Date('2024-01-13T15:00:00'),
        notes: 'Converted to order PO-RB-2024-2345',
      },
    ],
  },
  {
    id: 'quote-5',
    quote_number: 'Q-2024-1002',
    version: 1,
    status: 'rejected',
    customer: sampleCustomers[2],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-9',
        product: sampleProducts[0],
        quantity: 50,
        unit_price: 45.50,
        subtotal: 2275.00,
        confidence_score: 95,
      },
    ],
    billing_address: {
      street: '321 Steel Ave',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
    },
    subtotal: 2275.00,
    tax_rate: 0.0825,
    tax_amount: 187.69,
    tax_exempt: false,
    shipping_cost: 150.00,
    total: 2612.69,
    valid_until: new Date('2024-02-01'),
    created_at: new Date('2024-01-10T09:00:00'),
    updated_at: new Date('2024-01-12T16:00:00'),
    sent_at: new Date('2024-01-10T10:00:00'),
    rejected_at: new Date('2024-01-12T16:00:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2024-01-10T10:00:00'),
      },
      {
        from: 'sent' as QuoteStatus,
        to: 'rejected' as QuoteStatus,
        timestamp: new Date('2024-01-12T16:00:00'),
        notes: 'Price too high - went with competitor',
      },
    ],
    notes: 'Customer feedback: pricing not competitive',
  },
  {
    id: 'quote-6',
    quote_number: 'Q-2024-1003',
    version: 1,
    status: 'expired',
    customer: sampleCustomers[1],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-10',
        product: sampleProducts[2],
        quantity: 75,
        unit_price: 18.25,
        subtotal: 1368.75,
        confidence_score: 92,
      },
    ],
    billing_address: {
      street: '789 Industrial Blvd',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
    },
    subtotal: 1368.75,
    tax_rate: 0.0825,
    tax_amount: 112.92,
    tax_exempt: false,
    shipping_cost: 100.00,
    total: 1581.67,
    valid_until: new Date('2024-01-05'),
    created_at: new Date('2023-12-20T14:00:00'),
    updated_at: new Date('2024-01-06T00:00:00'),
    sent_at: new Date('2023-12-20T15:00:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2023-12-20T15:00:00'),
      },
      {
        from: 'sent' as QuoteStatus,
        to: 'expired' as QuoteStatus,
        timestamp: new Date('2024-01-06T00:00:00'),
        notes: 'Quote validity period expired',
      },
    ],
    notes: 'Follow up needed - customer showed interest',
  },
  {
    id: 'quote-7',
    quote_number: 'Q-2024-1004',
    version: 1,
    status: 'sent',
    customer: sampleCustomers[3],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-11',
        product: sampleProducts[1],
        quantity: 200,
        unit_price: 12.75,
        subtotal: 2550.00,
        confidence_score: 88,
      },
      {
        id: 'line-12',
        product: sampleProducts[3],
        quantity: 100,
        unit_price: 8.99,
        subtotal: 899.00,
        confidence_score: 90,
      },
    ],
    billing_address: {
      street: '567 Builder Way',
      city: 'San Antonio',
      state: 'TX',
      zip: '78201',
    },
    job_site_address: {
      street: '890 Project Site Rd',
      city: 'San Antonio',
      state: 'TX',
      zip: '78202',
    },
    project_name: 'Regional Mall Renovation',
    subtotal: 3449.00,
    tax_rate: 0,
    tax_amount: 0,
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-456',
    shipping_cost: 175.00,
    total: 3624.00,
    valid_until: new Date('2024-02-20'),
    created_at: new Date('2024-01-16T11:00:00'),
    updated_at: new Date('2024-01-16T11:30:00'),
    sent_at: new Date('2024-01-16T11:30:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2024-01-16T11:30:00'),
      },
    ],
    notes: 'Urgent - customer needs response by EOW',
  },
  {
    id: 'quote-8',
    quote_number: 'Q-2024-1005',
    version: 2,
    status: 'draft',
    customer: sampleCustomers[0],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-13',
        product: sampleProducts[4],
        quantity: 500,
        unit_price: 7.25,
        subtotal: 3625.00,
        confidence_score: 85,
      },
    ],
    billing_address: {
      street: '123 Main St',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
    },
    subtotal: 3625.00,
    tax_rate: 0,
    tax_amount: 0,
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-123',
    shipping_cost: 200.00,
    total: 3825.00,
    valid_until: new Date('2024-02-25'),
    created_at: new Date('2024-01-17T09:00:00'),
    updated_at: new Date('2024-01-17T10:15:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'draft' as QuoteStatus,
        timestamp: new Date('2024-01-17T09:00:00'),
      },
    ],
    notes: 'Waiting for customer input on specifications',
  },
  {
    id: 'quote-9',
    quote_number: 'Q-2024-1006',
    version: 1,
    status: 'accepted',
    customer: sampleCustomers[2],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-14',
        product: sampleProducts[0],
        quantity: 30,
        unit_price: 45.50,
        subtotal: 1365.00,
        confidence_score: 95,
      },
      {
        id: 'line-15',
        product: sampleProducts[2],
        quantity: 40,
        unit_price: 18.25,
        subtotal: 730.00,
        confidence_score: 92,
      },
    ],
    billing_address: {
      street: '321 Steel Ave',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
    },
    subtotal: 2095.00,
    tax_rate: 0.0825,
    tax_amount: 172.84,
    tax_exempt: false,
    shipping_cost: 125.00,
    total: 2392.84,
    valid_until: new Date('2024-02-15'),
    created_at: new Date('2024-01-14T10:00:00'),
    updated_at: new Date('2024-01-15T14:00:00'),
    sent_at: new Date('2024-01-14T11:00:00'),
    accepted_at: new Date('2024-01-15T14:00:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2024-01-14T11:00:00'),
      },
      {
        from: 'sent' as QuoteStatus,
        to: 'accepted' as QuoteStatus,
        timestamp: new Date('2024-01-15T14:00:00'),
        notes: 'PO# SS-2024-0789 received',
      },
    ],
    notes: 'Ready to convert to order',
  },
  {
    id: 'quote-10',
    quote_number: 'Q-2024-1007',
    version: 1,
    status: 'draft',
    customer: sampleCustomers[1],
    sales_rep: sampleSalesRep,
    line_items: [],
    billing_address: {
      street: '789 Industrial Blvd',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
    },
    subtotal: 0,
    tax_rate: 0.0825,
    tax_amount: 0,
    tax_exempt: false,
    shipping_cost: 0,
    total: 0,
    valid_until: new Date('2024-02-28'),
    created_at: new Date('2024-01-17T14:00:00'),
    updated_at: new Date('2024-01-17T14:00:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'draft' as QuoteStatus,
        timestamp: new Date('2024-01-17T14:00:00'),
      },
    ],
    notes: 'New quote - awaiting RFQ upload',
  },
]

// Sample orders
export const sampleOrders: Order[] = [
  {
    id: 'order-1',
    po_number: 'PO-RB-2024-2345',
    source: 'quote',
    source_metadata: {
      quote_id: 'quote-4',
      quote_number: 'Q-2024-0998',
    },
    confidence_score: 100,
    customer: sampleCustomers[3],
    line_items: [
      {
        id: 'order-line-1',
        product: sampleProducts[1],
        quantity: 100,
        unit_price: 12.75,
        subtotal: 1275.00,
        matched_product_id: 'prod-2',
        match_confidence: 100,
      },
      {
        id: 'order-line-2',
        product: sampleProducts[3],
        quantity: 75,
        unit_price: 8.99,
        subtotal: 674.25,
        matched_product_id: 'prod-4',
        match_confidence: 100,
      },
    ],
    billing_address: {
      street: '555 Builder Way',
      city: 'San Antonio',
      state: 'TX',
      zip: '78201',
    },
    shipping_address: {
      street: '1000 Project Rd',
      city: 'New Braunfels',
      state: 'TX',
      zip: '78130',
    },
    status: 'processing',
    subtotal: 1949.25,
    tax_amount: 0,
    shipping_cost: 175.00,
    total: 2124.25,
    created_at: new Date('2024-01-13T15:00:00'),
    updated_at: new Date('2024-01-13T15:05:00'),
    notes: 'Created from Q-2024-0998. Project: River Walk Extension',
  },
  {
    id: 'order-2',
    po_number: 'PO-BUILD-2024-567',
    source: 'email',
    source_metadata: {
      email_id: 'email-123',
      email_subject: 'Purchase Order - Urgent',
    },
    confidence_score: 78,
    customer: sampleCustomers[1],
    line_items: [
      {
        id: 'order-line-3',
        product: sampleProducts[4],
        quantity: 200,
        unit_price: 7.25,
        subtotal: 1450.00,
        matched_product_id: 'prod-5',
        match_confidence: 75,
      },
    ],
    billing_address: {
      street: '789 Industrial Blvd',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
    },
    status: 'pending',
    subtotal: 1450.00,
    tax_amount: 119.63,
    shipping_cost: 100.00,
    total: 1669.63,
    created_at: new Date('2024-01-15T11:00:00'),
    updated_at: new Date('2024-01-15T11:00:00'),
    notes: 'Extracted from email. Manual review recommended.',
  },
  {
    id: 'order-3',
    po_number: 'EDI-2024-88923',
    source: 'edi',
    source_metadata: {
      edi_transaction: '850-88923',
    },
    confidence_score: 95,
    customer: sampleCustomers[0],
    line_items: [
      {
        id: 'order-line-4',
        product: sampleProducts[2],
        quantity: 150,
        unit_price: 18.25,
        subtotal: 2737.50,
        matched_product_id: 'prod-3',
        match_confidence: 98,
      },
    ],
    billing_address: {
      street: '123 Main St',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
    },
    status: 'approved',
    subtotal: 2737.50,
    tax_amount: 0,
    shipping_cost: 200.00,
    total: 2937.50,
    created_at: new Date('2024-01-15T08:00:00'),
    updated_at: new Date('2024-01-15T08:30:00'),
    processed_at: new Date('2024-01-15T08:30:00'),
    notes: 'EDI 850 transaction processed automatically',
  },
]

// Analytics data
export const analyticsData = {
  quotesThisWeek: 47,
  acceptanceRate: 76,
  acceptanceRateTrend: 'up' as const,
  avgTimeToAccept: 2.3, // hours
  revenuePipeline: 247000,
  topProducts: [
    { name: 'PVC Pipe', revenue: 45000 },
    { name: 'Portland Cement', revenue: 38000 },
    { name: 'Rebar', revenue: 32000 },
  ],
  conversionBySource: {
    quote: 100,
    email: 78,
    edi: 95,
    api: 92,
  },
}

// Sample invoices for AR management
export const sampleInvoices: CustomerInvoice[] = [
  {
    id: 'inv-1',
    invoice_number: 'INV-2024-0892',
    invoice_date: new Date('2024-01-26'),
    due_date: new Date('2024-01-26'), // Due today
    order_id: 'order-1',
    customer_id: 'cust-2',
    customer: sampleCustomers[1], // BuildCo Inc
    po_number: 'PO-445821',
    project_name: 'Tower-5 Construction',
    progress_billing: {
      contract_value: 101733,
      percent_complete: 45,
      previous_billings: 20346,
      retention_percent: 10,
      retention_amount: 4578,
      current_billing: 45780,
      remaining_value: 55953,
    },
    subtotal: 50866,
    tax_amount: 4197,
    tax_rate: 0.0825,
    shipping_cost: 0,
    discount_amount: 1205,
    retention_withheld: 4578,
    total_amount: 45780,
    amount_paid: 0,
    balance_due: 45780,
    status: 'sent',
    payment_terms: 'NET30',
    days_overdue: 0,
    line_items: [],
    lien_waiver_status: 'conditional_sent',
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-26'),
    sent_at: new Date('2024-01-10'),
  },
  {
    id: 'inv-2',
    invoice_number: 'INV-2024-0891',
    invoice_date: new Date('2024-01-10'),
    due_date: new Date('2024-03-11'),
    order_id: 'order-2',
    customer_id: 'cust-3',
    customer: sampleCustomers[2], // ACME Construction
    po_number: 'PO-445677',
    project_name: 'Mall-X Renovation',
    progress_billing: {
      contract_value: 425000,
      percent_complete: 50,
      previous_billings: 85000,
      retention_percent: 10,
      retention_amount: 12745,
      current_billing: 127450,
      remaining_value: 212550,
    },
    subtotal: 131757,
    tax_amount: 10870,
    tax_rate: 0.0825,
    shipping_cost: 0,
    discount_amount: 0,
    retention_withheld: 12745,
    total_amount: 127450,
    amount_paid: 0,
    balance_due: 114705,
    status: 'overdue',
    payment_terms: 'NET60',
    days_overdue: 15,
    line_items: [
      {
        id: 'line-1',
        sku: 'CONC-4000',
        description: 'Ready Mix Concrete 4000 PSI',
        quantity: 450,
        unit: 'yd³',
        unit_price: 125,
        extended_amount: 56250,
      },
      {
        id: 'line-2',
        sku: 'REBAR-#5',
        description: '#5 Rebar Grade 60',
        quantity: 8500,
        unit: 'lb',
        unit_price: 0.85,
        extended_amount: 7225,
      },
    ],
    lien_waiver_status: 'conditional_sent',
    preliminary_notice_date: new Date('2024-01-05'),
    created_at: new Date('2024-01-10'),
    updated_at: new Date('2024-01-26'),
    sent_at: new Date('2024-01-10'),
    last_reminder_at: new Date('2024-01-19'),
  },
  {
    id: 'inv-3',
    invoice_number: 'INV-2024-0890',
    invoice_date: new Date('2024-01-08'),
    due_date: new Date('2024-01-28'),
    order_id: 'order-3',
    customer_id: 'cust-1',
    customer: sampleCustomers[0], // Enterprise Construction
    po_number: 'PO-445599',
    project_name: 'Hotel-A Plumbing',
    subtotal: 34200,
    tax_amount: 2821,
    tax_rate: 0.0825,
    shipping_cost: 0,
    discount_amount: 684, // 2% early payment discount available
    retention_withheld: 0,
    total_amount: 34200,
    amount_paid: 0,
    balance_due: 34200,
    status: 'sent',
    payment_terms: '2/10NET30',
    line_items: [],
    lien_waiver_status: 'preliminary_sent',
    created_at: new Date('2024-01-08'),
    updated_at: new Date('2024-01-08'),
    sent_at: new Date('2024-01-08'),
  },
  {
    id: 'inv-4',
    invoice_number: 'INV-2024-0889',
    invoice_date: new Date('2024-01-05'),
    due_date: new Date('2024-02-19'),
    order_id: 'order-4',
    customer_id: 'cust-4',
    customer: sampleCustomers[0], // Using Enterprise as placeholder
    po_number: 'PO-445512',
    project_name: 'School-B Electrical',
    subtotal: 78920,
    tax_amount: 6511,
    tax_rate: 0.0825,
    shipping_cost: 0,
    discount_amount: 0,
    retention_withheld: 0,
    total_amount: 78920,
    amount_paid: 40000,
    balance_due: 38920,
    status: 'partial',
    payment_terms: 'NET45',
    line_items: [],
    created_at: new Date('2024-01-05'),
    updated_at: new Date('2024-01-20'),
    sent_at: new Date('2024-01-05'),
    paid_at: new Date('2024-01-20'),
  },
  {
    id: 'inv-5',
    invoice_number: 'INV-2024-0888',
    invoice_date: new Date('2024-01-04'),
    due_date: new Date('2024-02-03'),
    order_id: 'order-5',
    customer_id: 'cust-2',
    customer: sampleCustomers[1], // BuildCo
    po_number: 'PO-445490',
    project_name: 'Arena-C Stone Work',
    progress_billing: {
      contract_value: 782233,
      percent_complete: 30,
      previous_billings: 0,
      retention_percent: 10,
      retention_amount: 23467,
      current_billing: 234670,
      remaining_value: 547563,
    },
    subtotal: 260744,
    tax_amount: 21511,
    tax_rate: 0.0825,
    shipping_cost: 0,
    discount_amount: 0,
    retention_withheld: 23467,
    total_amount: 234670,
    amount_paid: 0,
    balance_due: 234670,
    status: 'draft',
    payment_terms: 'NET30',
    line_items: [],
    created_at: new Date('2024-01-04'),
    updated_at: new Date('2024-01-04'),
  },
]