import type { Quote, Order, Customer, SalesRep, Product, QuoteStatus, OrderStatus } from './types'

// Sample customers
export const sampleCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'ACME Construction',
    email: 'purchasing@acmeconstruction.com',
    phone: '512-555-0100',
    type: 'B2B Contractor',
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-123',
    credit_limit: 50000,
  },
  {
    id: 'cust-2',
    name: 'BuildCo Inc',
    email: 'orders@buildco.com',
    phone: '512-555-0200',
    type: 'Distributor',
    tax_exempt: false,
    credit_limit: 100000,
  },
  {
    id: 'cust-3',
    name: 'Steel Supply Co',
    email: 'procurement@steelsupply.com',
    phone: '512-555-0300',
    type: 'Retailer',
    tax_exempt: false,
    credit_limit: 25000,
  },
  {
    id: 'cust-4',
    name: 'Regional Builders',
    email: 'buying@regionalbuilders.com',
    phone: '512-555-0400',
    type: 'B2B Contractor',
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-456',
    credit_limit: 75000,
  },
]

// Sample sales rep
export const sampleSalesRep: SalesRep = {
  id: 'rep-1',
  name: 'Sarah Chen',
  email: 'sarah.chen@camber.ai',
  phone: '512-555-0001',
}

// Sample products
export const sampleProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'PVC-12',
    name: '12" PVC Pipe',
    description: 'Schedule 40 PVC pipe, 12 inch diameter, 20ft length',
    unit_price: 45.50,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 150,
  },
  {
    id: 'prod-2',
    sku: 'CEMENT-50',
    name: 'Portland Cement 50lb',
    description: 'Type I/II Portland cement, 50 pound bag',
    unit_price: 12.75,
    unit_of_measure: 'BAG',
    inventory_status: 'low_stock',
    available_quantity: 20,
    lead_time_days: 3,
  },
  {
    id: 'prod-3',
    sku: 'REBAR-20',
    name: '#5 Rebar 20ft',
    description: '5/8" diameter reinforcing steel bar, 20 foot length',
    unit_price: 18.25,
    unit_of_measure: 'EA',
    inventory_status: 'in_stock',
    available_quantity: 500,
  },
  {
    id: 'prod-4',
    sku: 'CONC-MIX',
    name: 'Concrete Mix 80lb',
    description: 'Pre-mixed concrete, just add water, 80 pound bag',
    unit_price: 8.99,
    unit_of_measure: 'BAG',
    inventory_status: 'in_stock',
    available_quantity: 200,
  },
  {
    id: 'prod-5',
    sku: 'LUMBER-2X4',
    name: '2x4 Lumber 8ft',
    description: 'Standard framing lumber, 2x4x8 feet, pressure treated',
    unit_price: 7.25,
    unit_of_measure: 'EA',
    inventory_status: 'out_of_stock',
    lead_time_days: 7,
  },
]

// Sample quotes with different statuses
export const sampleQuotes: Quote[] = [
  {
    id: 'quote-1',
    quote_number: 'Q-2024-1001',
    version: 1,
    status: 'draft',
    customer: sampleCustomers[0],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-1',
        product: sampleProducts[0],
        quantity: 25,
        unit_price: 45.50,
        subtotal: 1137.50,
        confidence_score: 95,
      },
      {
        id: 'line-2',
        product: sampleProducts[1],
        quantity: 15,
        unit_price: 12.75,
        subtotal: 191.25,
        confidence_score: 88,
      },
    ],
    billing_address: {
      street: '123 Main St',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
    },
    job_site_address: {
      street: '456 Construction Way',
      city: 'Round Rock',
      state: 'TX',
      zip: '78664',
    },
    project_name: 'Westlake Office Complex - Phase 2',
    subtotal: 1328.75,
    discount: {
      percentage: 5,
      amount: 66.44,
      reason: 'Volume discount',
    },
    tax_rate: 0,
    tax_amount: 0,
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-123',
    shipping_cost: 125.00,
    total: 1387.31,
    valid_until: new Date('2024-02-15'),
    created_at: new Date('2024-01-15T10:30:00'),
    updated_at: new Date('2024-01-15T10:30:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'draft' as QuoteStatus,
        timestamp: new Date('2024-01-15T10:30:00'),
      },
    ],
    notes: 'Customer requested delivery by end of month',
  },
  {
    id: 'quote-2',
    quote_number: 'Q-2024-1000',
    version: 2,
    status: 'sent',
    customer: sampleCustomers[1],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-3',
        product: sampleProducts[2],
        quantity: 100,
        unit_price: 18.25,
        subtotal: 1825.00,
        confidence_score: 92,
      },
      {
        id: 'line-4',
        product: sampleProducts[3],
        quantity: 50,
        unit_price: 8.99,
        subtotal: 449.50,
        confidence_score: 90,
      },
    ],
    billing_address: {
      street: '789 Industrial Blvd',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
    },
    subtotal: 2274.50,
    tax_rate: 0.0825,
    tax_amount: 187.65,
    tax_exempt: false,
    shipping_cost: 200.00,
    total: 2662.15,
    valid_until: new Date('2024-02-10'),
    created_at: new Date('2024-01-15T09:00:00'),
    updated_at: new Date('2024-01-15T09:30:00'),
    sent_at: new Date('2024-01-15T09:30:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'draft' as QuoteStatus,
        timestamp: new Date('2024-01-15T09:00:00'),
      },
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2024-01-15T09:30:00'),
        changed_by: 'Sarah Chen',
      },
    ],
  },
  {
    id: 'quote-3',
    quote_number: 'Q-2024-0999',
    version: 1,
    status: 'accepted',
    customer: sampleCustomers[2],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-5',
        product: sampleProducts[0],
        quantity: 50,
        unit_price: 45.50,
        subtotal: 2275.00,
        confidence_score: 98,
      },
    ],
    billing_address: {
      street: '321 Commerce St',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
    },
    subtotal: 2275.00,
    tax_rate: 0.0825,
    tax_amount: 187.69,
    tax_exempt: false,
    shipping_cost: 150.00,
    total: 2612.69,
    valid_until: new Date('2024-02-05'),
    created_at: new Date('2024-01-14T14:00:00'),
    updated_at: new Date('2024-01-14T16:00:00'),
    sent_at: new Date('2024-01-14T14:30:00'),
    accepted_at: new Date('2024-01-14T16:00:00'),
    status_history: [
      {
        from: 'draft' as QuoteStatus,
        to: 'sent' as QuoteStatus,
        timestamp: new Date('2024-01-14T14:30:00'),
      },
      {
        from: 'sent' as QuoteStatus,
        to: 'accepted' as QuoteStatus,
        timestamp: new Date('2024-01-14T16:00:00'),
        changed_by: 'John Smith',
        notes: 'PO# SS-2024-789',
      },
    ],
  },
  {
    id: 'quote-4',
    quote_number: 'Q-2024-0998',
    version: 1,
    status: 'converted',
    customer: sampleCustomers[3],
    sales_rep: sampleSalesRep,
    line_items: [
      {
        id: 'line-6',
        product: sampleProducts[1],
        quantity: 100,
        unit_price: 12.75,
        subtotal: 1275.00,
        confidence_score: 100,
      },
      {
        id: 'line-7',
        product: sampleProducts[3],
        quantity: 75,
        unit_price: 8.99,
        subtotal: 674.25,
        confidence_score: 100,
      },
    ],
    billing_address: {
      street: '555 Builder Way',
      city: 'San Antonio',
      state: 'TX',
      zip: '78201',
    },
    job_site_address: {
      street: '1000 Project Rd',
      city: 'New Braunfels',
      state: 'TX',
      zip: '78130',
    },
    project_name: 'River Walk Extension',
    subtotal: 1949.25,
    tax_rate: 0,
    tax_amount: 0,
    tax_exempt: true,
    tax_exemption_number: 'TX-EXEMPT-456',
    shipping_cost: 175.00,
    total: 2124.25,
    valid_until: new Date('2024-02-01'),
    created_at: new Date('2024-01-13T10:00:00'),
    updated_at: new Date('2024-01-13T15:00:00'),
    sent_at: new Date('2024-01-13T10:30:00'),
    accepted_at: new Date('2024-01-13T14:00:00'),
    converted_at: new Date('2024-01-13T15:00:00'),
    status_history: [
      {
        from: 'sent' as QuoteStatus,
        to: 'accepted' as QuoteStatus,
        timestamp: new Date('2024-01-13T14:00:00'),
        changed_by: 'Mike Johnson',
        notes: 'PO# RB-2024-2345',
      },
      {
        from: 'accepted' as QuoteStatus,
        to: 'converted' as QuoteStatus,
        timestamp: new Date('2024-01-13T15:00:00'),
        notes: 'Converted to order PO-RB-2024-2345',
      },
    ],
  },
]

// Sample orders
export const sampleOrders: Order[] = [
  {
    id: 'order-1',
    po_number: 'PO-RB-2024-2345',
    source: 'quote',
    source_metadata: {
      quote_id: 'quote-4',
      quote_number: 'Q-2024-0998',
    },
    confidence_score: 100,
    customer: sampleCustomers[3],
    line_items: [
      {
        id: 'order-line-1',
        product: sampleProducts[1],
        quantity: 100,
        unit_price: 12.75,
        subtotal: 1275.00,
        matched_product_id: 'prod-2',
        match_confidence: 100,
      },
      {
        id: 'order-line-2',
        product: sampleProducts[3],
        quantity: 75,
        unit_price: 8.99,
        subtotal: 674.25,
        matched_product_id: 'prod-4',
        match_confidence: 100,
      },
    ],
    billing_address: {
      street: '555 Builder Way',
      city: 'San Antonio',
      state: 'TX',
      zip: '78201',
    },
    shipping_address: {
      street: '1000 Project Rd',
      city: 'New Braunfels',
      state: 'TX',
      zip: '78130',
    },
    status: 'processing',
    subtotal: 1949.25,
    tax_amount: 0,
    shipping_cost: 175.00,
    total: 2124.25,
    created_at: new Date('2024-01-13T15:00:00'),
    updated_at: new Date('2024-01-13T15:05:00'),
    notes: 'Created from Q-2024-0998. Project: River Walk Extension',
  },
  {
    id: 'order-2',
    po_number: 'PO-BUILD-2024-567',
    source: 'email',
    source_metadata: {
      email_id: 'email-123',
      email_subject: 'Purchase Order - Urgent',
    },
    confidence_score: 78,
    customer: sampleCustomers[1],
    line_items: [
      {
        id: 'order-line-3',
        product: sampleProducts[4],
        quantity: 200,
        unit_price: 7.25,
        subtotal: 1450.00,
        matched_product_id: 'prod-5',
        match_confidence: 75,
      },
    ],
    billing_address: {
      street: '789 Industrial Blvd',
      city: 'Houston',
      state: 'TX',
      zip: '77001',
    },
    status: 'pending',
    subtotal: 1450.00,
    tax_amount: 119.63,
    shipping_cost: 100.00,
    total: 1669.63,
    created_at: new Date('2024-01-15T11:00:00'),
    updated_at: new Date('2024-01-15T11:00:00'),
    notes: 'Extracted from email. Manual review recommended.',
  },
  {
    id: 'order-3',
    po_number: 'EDI-2024-88923',
    source: 'edi',
    source_metadata: {
      edi_transaction: '850-88923',
    },
    confidence_score: 95,
    customer: sampleCustomers[0],
    line_items: [
      {
        id: 'order-line-4',
        product: sampleProducts[2],
        quantity: 150,
        unit_price: 18.25,
        subtotal: 2737.50,
        matched_product_id: 'prod-3',
        match_confidence: 98,
      },
    ],
    billing_address: {
      street: '123 Main St',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
    },
    status: 'approved',
    subtotal: 2737.50,
    tax_amount: 0,
    shipping_cost: 200.00,
    total: 2937.50,
    created_at: new Date('2024-01-15T08:00:00'),
    updated_at: new Date('2024-01-15T08:30:00'),
    processed_at: new Date('2024-01-15T08:30:00'),
    notes: 'EDI 850 transaction processed automatically',
  },
]

// Analytics data
export const analyticsData = {
  quotesThisWeek: 47,
  acceptanceRate: 76,
  acceptanceRateTrend: 'up' as const,
  avgTimeToAccept: 2.3, // hours
  revenuePipeline: 247000,
  topProducts: [
    { name: 'PVC Pipe', revenue: 45000 },
    { name: 'Portland Cement', revenue: 38000 },
    { name: 'Rebar', revenue: 32000 },
  ],
  conversionBySource: {
    quote: 100,
    email: 78,
    edi: 95,
    api: 92,
  },
}